/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/M9C4CAUiArt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import Link from "next/link"
import Image from "next/image"

export default function Component() {
    return (
        <main className="w-full h-full flex flex-row  ">
            <div className="hidden w-1/2 p-8 md:block">
                <img src="/signup.png" alt="Illustration" className=" w-full h-full" />
            </div>
            <div className="flex flex-grow items-center justify-center ">

                <div className="flex flex-col items-center justify-center  w-1/2">
                    <h2 className="mb-8 text-3xl font-bold text-center text-[#183B56]">Welcome back.</h2>
                    <Button className="w-full px-1.5 py-6 mb-4 bg-[#1565D8] flex flex-row hover:bg-blue-500 text-white">
                        <div className="w-9 h-9 bg-white p-1.5 rounded">
                            <img src="./google.png" />
                        </div>
                        <span className="flex-grow font-semibold">Sign in with Google</span>
                    </Button>
                    <div className="flex items-center justify-center w-full mb-4">
                        <span className="flex-grow h-px bg-[#E5EAF4]" />
                        <span className="px-4 text-sm text-[#183B56] font-medium">Or, sign in with your email</span>
                        <span className="flex-grow h-px bg-[#E5EAF4]" />
                    </div>
                    <div className="w-full mb-4 space-y-1.5">
                        <Label htmlFor="email" className="text-[#5A7184]">Email address*</Label>
                        <Input id="email" type="email" placeholder="Enter your Email" className="w-full text-[#183B56] font-medium" />
                    </div>
                    <div className="w-full mb-4 space-y-1.5">
                        <Label htmlFor="password" className="text-[#5A7184]">Password*</Label>
                        <Input id="password" type="password" placeholder="Enter password" className="w-full text-[#183B56] font-medium" />
                    </div>
                    <div className="flex items-center justify-between w-full mb-6">
                        <div className="flex items-center">
                            <Checkbox id="keep-me-signin" className="" />
                            <Label htmlFor="keep-me-signin" className="ml-2 text-sm">
                                Keep Me Sign in
                            </Label>
                        </div>
                    </div>
                    <Button className="w-full py-6 bg-[#1565D8] hover:bg-blue-500 font-semibold text-white">Sign in</Button>
                    <div className="mt-6 text-center w-full">
                        <span className="text-sm text-gray-500">Don't have an account? </span>
                        <Link href="#" className="text-sm text-blue-600" prefetch={false}>
                            Signup now
                        </Link>
                    </div>
                </div>
            </div>

        </main>

    )
}


