services:
  app:
    build: ..
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres123@postgres:5432/postgres"
      DEBUG: "false"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: