/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/M9C4CAUiArt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import Link from "next/link"

export default function Component() {
    return (
        <div className="flex  items-center justify-center bg-gray-100">
            <div className="hidden md:block">
                <img src="/signup.png" alt="Illustration" className="py-64 object-cover w-full h-screen" />
            </div>
            <div className="w-full p-8 md:w-1/2">
                <h2 className="mb-6 text-3xl font-bold text-center">Welcome back.</h2>
                <Button className="w-full mb-4 bg-blue-600 text-white">
                    <ChromeIcon className="mr-2 h-5 w-5" />
                    Sign in with Google
                </Button>
                <div className="flex items-center justify-center mb-4">
                    <span className="w-full h-px bg-gray-300" />
                    <span className="px-4 text-sm text-gray-500">Or, sign in with your email</span>
                    <span className="w-full h-px bg-gray-300" />
                </div>
                <div className="mb-4">
                    <Label htmlFor="email">Email address</Label>
                    <Input id="email" type="email" placeholder="Email" defaultValue="gilroybworn@gmail.com" />
                </div>
                <div className="mb-4">
                    <Label htmlFor="password">Password</Label>
                    <Input id="password" type="password" placeholder="Enter password" />
                </div>
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center">
                        <Checkbox id="keep-signed-in" />
                        <Label htmlFor="keep-signed-in" className="ml-2 text-sm">
                            Keep me signed in
                        </Label>
                    </div>
                    <Link href="#" className="text-sm text-blue-600" prefetch={false}>
                        Forgot password?
                    </Link>
                </div>
                <Button className="w-full bg-blue-600 text-white">Sign in</Button>
                <div className="mt-6 text-center">
                    <span className="text-sm text-gray-500">Don't have an account? </span>
                    <Link href="#" className="text-sm text-blue-600" prefetch={false}>
                        Sign up now
                    </Link>
                </div>
            </div>
        </div>
    )
}

function ChromeIcon(props: any) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="12" cy="12" r="10" />
            <circle cx="12" cy="12" r="4" />
            <line x1="21.17" x2="12" y1="8" y2="8" />
            <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
            <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
        </svg>
    )
}
